#!/bin/sh
set -e

sed -i 's/use-ipv6=yes/use-ipv6=no/' /etc/avahi/avahi-daemon.conf
sed -i 's/#enable-dbus=yes/enable-dbus=no/' /etc/avahi/avahi-daemon.conf
sed -i 's/#use-iff-running=no/use-iff-running=yes/' /etc/avahi/avahi-daemon.conf
sed -i 's/#enable-reflector=no/enable-reflector=yes/' /etc/avahi/avahi-daemon.conf

exit 0
